spring:
  datasource:
    url: jdbc:h2:mem:spending-bot
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
app:
  telegram:
    processor:
      maxMessageTime: 30
      defaultProcessorMessage: Данная команда не распознана или не поддерживается
      errorProcessorMessage: Произошла неожиданная ошибка при обработке сообщения. Не делайте так больше пожалуйста :)
      helpProcessorMessage: |
        Поддреживаемые команды:
        /help - Помощь
        /add - Добавление операции. Добавление операции происходит в интерактивном режиме. Вам только требуется следовать инструкциям в чате. Если вы хотите прервать ввод просто введите занк # если хотите оставить поле пустым введите *
        /balance - запрос баланса
        /plans - Запланированные на сегодня операции
        /auth - авторизация
        /last список последних операций. По умолчанию выводится 5 штук. Если требуется другое количество можно ввести после команды например:
        /last 10 выведет 10 последних операций
        /sign - Подписаться на уведомления по операциям
        /unsign - отписаться от уведомлений по операциям
    bot:
      name: SpendingBot
      token:
      proxyHost:
      proxyPort:
      proxyType:
      proxyUser:
      proxyPassword:
